.SUFFIXES: .plm .pro

ABIN = $(AMZI_DEV_DIR)/abin/
ALIB = $(AMZI_DEV_DIR)/abin/alib.plm
AREG = $(AMZI_DEV_DIR)/src/acore/compile/register.plm

OBJECTS = alis.plm debug.plm listen.plm $(AREG)

all: $(ABIN)alis.xpl

.pro.plm:
	acmp $<

$(ABIN)alis.xpl : $(ALIB) $(OBJECTS)
	alnk $(ABIN)alis $(OBJECTS)

clean :
	rm *.plm
	